# Generated by Django 5.2.9 on 2025-12-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operation',
            name='op_type',
            field=models.CharField(choices=[('Export', 'Експорт'), ('Import', 'Імпорт')], max_length=10),
        ),
        migrations.AlterField(
            model_name='operation',
            name='partner_country',
            field=models.CharField(max_length=100),
        ),
    ]
